### ISSUE TITLE
[Enhancement] Exclude adding labels from the list of when looking calculating days until stale

### ISSUE THREAD

**Issue by PallasMedia** [actions/stale#106]
When an issue is created in our repo we have someone (aka me) who goes through and adds all the labels to the issue that applies to it. This is more maintenance than anything so it's easy for people to find what they're looking for and has no relation to the issue that was created. I know the action currently looks at all activity when it calculates how many days it's been since last activity. I'd like the ability to exclude adding labels from this list.

**Comment by hross** [comment]
In order to not overcomplicate the mechanisms we have I don't think we would want that as an enhancement. 

I know it's an annoyance, but I'd like to avoid too many options that overcomplicate the logic (for example you could have other actions that might also exclude staleness and then options for each).

I am going to close this for now. If there is a lot of feedback that this is desired we can reopen it.

**Comment by hross** [comment]
This actually might be an easy way to address this issue: https://github.com/actions/stale/issues/136

Exempt labels wouldn't count and there is already logic for them

**Comment by PallasStreams** [comment]
If I'm not mistaken though exempt labels prevents them from ever being marked as stale. Am I correct in that statement? If I am then that's not my goal. My goal here is so that if I assign a label to the issue but don't leave a comment the date the bot should mark as stale is still the date the number of days after the opening date. If someone leaves a comment then sure extend the date but I don't think a project manager assigning a label to the issue or assigning the issue to a person should extend it or at least I think there should be an option I can enable so that it doesn't as that may not be what everyone wants.

**Comment by hross** [comment]
Yes that's correct. I'll reopen this for feedback but if it complicates the configuration more I'm not sure it's worth addressing right now.

**Comment by PallasStreams** [comment]
Is there anything further you need from me on this? So far only you and I have discussed this issue.

**Comment by hross** [comment]
There is nothing further needed on this issue except to either implement it or not (and get feedback from others who might want to comment).

Right now I don't think I would add it just based on time/complexity and desire for the feature.
