### ISSUE TITLE
Post stale message regularly

### ISSUE THREAD

**Issue by ran-huang** [actions/stale#321]
Hi, thank you for your great work!

Is there a way to post a message to a stale issue on a regular basis but never really close it? This workflow can sort of act as a reminder.

**Comment by C0ZEN** [comment]
@ran-huang there is no feature to do that and I don't see a good hack with the cron or the config to achieve that.

It can be possible to add a new option to send the stale warning message each day but in fact it depends on your cron config - if you run it one time per day or more.

Having a new option to send the stale warning message each time the stale action is run can be a better option eventually.
Note that it can be a problem though because the GitHub API restrictions will hit way sooner and probably your project will end-up with unprocessed issues in that case 😞

**Comment by ran-huang** [comment]
OK. Thank you for explaining that. 😺

**Comment by C0ZEN** [comment]
Are you really that this is a feature you need @ran-huang? Because the spam will be insane in such case

**Comment by ran-huang** [comment]
I was hoping that the action can keep sending stale messages at a specified interval (such as every 10 days), so every now and then I am notified that there's a stale issue. The spam would be limited. 

The current problem is, if I simply add an exempt-label to an issue that I can't fix right now, the action stops checking this issue, so I will not receive any more messages about it; after a while, the issue would be permanently taken out of my mind... 😞 That's why I mentioned using this action as a reminder: keep posting stale messages once in a while, but don't close the issue.

I'm not sure if you're interested in making such a feature. But if you do, I'd appreciate your help.

**Comment by C0ZEN** [comment]
@ran-huang I am always keen to help but only when I am sure about what to code and with that feature I am not 😞 
An option to send a "reminder" message "x days" could be one good thing based on your needs but to define "when" the message should be sent I think it's a bit harder because to know this information, I think the stale action should look into the comments, check if the message (checking the text) was sent if so, check when and define if it needs to be sent or not once again.
But for example if you delete the message to have a cleaner issue/pr the next time the action run it will send it once again so it's very annoying so this is not perfect.

**Comment by ran-huang** [comment]
You are right. Thanks for explaining that to me. I'll close this issue 😺

**Comment by C0ZEN** [comment]
@ran-huang I am just a contributor if I can but there are others too so even if I didn't find a good way to implement this it doesn't mean that there is none.
So I think that you can keep it opened - if you can't, maybe reopen a new one?

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by idbrii** [comment]
The docs show:

> Configure different stale timeouts but never close a PR:
> ...
>           days-before-pr-close: -1

So maybe you could post stale messages with:

          days-before-issue-stale: 10
          days-before-pr-stale: 10
          days-before-pr-close: -1
          days-before-issue-close: -1

You'd have to remove the label after each message to get another one.

**Comment by C0ZEN** [comment]
up

**Comment by luketomlinson** [comment]
Thanks for opening an issue @ran-huang. I think this feature would likely be better suited to another custom action. I think this is more akin to a "reminder" action than it is to a "stale" action. Perhaps a custom "reminder" action could inspect whether the issue has a stale label and send a periodic reminder. But I think this is a bit too specific and would complicate the purpose of the stale action.
