### ISSUE TITLE
[Feature Request] Support wildcards in labels

### ISSUE THREAD

**Issue by cmccandless** [actions/stale#326]
It would be nice to be able to specify wildcards for issue labels. For example, if a repo used labels such as:

- bug/UI
- bug/notifier
- bug/server

It would be helpful to be able to configure `exempt-issue-labels: 'bug/*'`

**Comment by C0ZEN** [comment]
@cmccandless I like this idea but I am wondering if this is a good idea or not to do that with or without a new option to "process" the label as a wildcard.
Maybe I am overthinking it but if we truly want to handle wildcards I do prefer to use a dependency to do that handling all the possible syntaxes and maybe it could break a stale configuration for people using it.
What do you think?

**Comment by cmccandless** [comment]
I think an `enable-label-wildcards: true` is reasonable to avoid breaking existing workflows.

**Comment by C0ZEN** [comment]
https://github.com/sindresorhus/matcher seems a good candidate to me

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
@hross @luketomlinson, do you think it's better to support regexp for the options or should the stale configuration have a new option to enable/disable the support of regexp?
In the first case, it's a breaking change and a major release would be preferable, but I think it's more natural as well as complicated due to special characters already present in most labels from the repositories.

**Comment by cmccandless** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by djavorek** [comment]
up
