### ISSUE TITLE
Allow users to re-open issues marked stale?

### ISSUE THREAD

**Issue by kevinushey** [actions/stale#345]
Currently, if the stale bot closes an issue, a member of the repository needs to re-open the issue if required. It might be useful to allow the OP of an issue to re-open their own stale issues; e.g. with a special phrase in their commit message (`!stalebot reopen`).

**Comment by kevinushey** [comment]
Note: ideally I think this would happen in https://github.com/isaacs/github/issues/583, but presumedly having a bot that implements this behavior would also be a way forward.

**Comment by C0ZEN** [comment]
@kevinushey basically, you wish to use the bot as a hack to this lack of implementation since it has the rights to do so?
It can be possible I think.

One thing though:
- The bot should only reopen if it was close by itself

And as you mentioned it would be better to avoid unnecessary reopening and un-closing only on specific occasion. With a message is one way to do it.
In that case, the message triggering the un-close should be part of a new option (unset means it's not possible to un-close, set means the workflow should look for it).
It gives the freedom to each consumer of this workflow to define what is the trigger.
The message to look for should be only from after the close date (to avoid issue like closed one time, re-opened then closed a second time and immediately re-opened).

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by C0ZEN** [comment]
up

**Comment by BillTiT** [comment]
Some issues should receive precedent over others based on overall effect on user environment

**Comment by luketomlinson** [comment]
I think this is out of scope for this action. We don't intend to make make the stale action interactive in this way.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/actions/stale/issues/345#event-5009046742

@luketomlinson, not planned, not completed, then.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/actions/stale/issues/345#issuecomment-878480179

@luketomlinson, why? I ask because I have had https://github.com/github/markup/issues/1857#event-14656408821 and https://github.com/github/markup/issues/1853#event-14619483323 closed merely because I was unavailable whilst attending RAF BRTC. That seems incredibly unfair.
