### ISSUE TITLE
Issue closed `close period` days after reopen

### ISSUE THREAD

**Issue by TheOneRing** [actions/stale#351]
The issue https://github.com/owncloud/client/issues/8365 was closed automatically 8 days after it was reopened. 
Without any previous stale message

**Comment by C0ZEN** [comment]
@TheOneRing I added a reproduction in the tests and basically the culprit here is that the issue was reopened without removing the stale label.
I was not aware of this and in fact I think it's awesome because it can close https://github.com/actions/stale/issues/188 IMO.

I thought that only the updateAt/last comment was a requirement to know if it's stale or not but in fact having a stale label influence the action and has a better priority.
What do you think?

On the other hand, it can be convenient to have eventually a feature which remove the stale label for you when the issue/PR is reopen but in that case opening a new issue for that would be better.

**Comment by TheOneRing** [comment]
Yes but I would expect a message that #xxx is going to be closed in 7 days because of reasons :)

**Comment by C0ZEN** [comment]
@TheOneRing IMO the best option to solve this is to remove the stale label after reopening.
Basically reopening means that it's a keeper so it's kinda opposite to letting it be stale.
It could be made with an option and if disabled instead send once again the message saying that it will be closed in x days.
Is this ok for you?

**Comment by TheOneRing** [comment]
Option two sounds handy, as this behavior should also cause a message on manually labeled issue?

**Comment by C0ZEN** [comment]
@TheOneRing yes, I think the only missing piece is the comment when you manually label as stale.
And I also think also that the best solutwould be to remove the stale label once closed.
