### ISSUE TITLE
Option to ignore draft PRs

### ISSUE THREAD

**Issue by Cyberboss** [actions/stale#36]
It would be nice to have the option to ignore draft PRs as they are implied to be not ready and can be filtered out.

**Comment by hross** [comment]
Thanks for the bump. I do like this idea and it is probably pretty easy to implement and test. Will take a look...

**Comment by hross** [comment]
I went back to our issues API and it doesn't include draft for pull requests, which means making extra calls for every PR to see if it is draft. So while I love this idea I don't think it's worth making the extra changes to deal with draft PRs right now.

**Comment by brianeclow** [comment]
Closing draft PRs is frustratingly annoying, that coupled with #98, the inability to have spaces in labels, the stale action closed a bunch of PRs that it shouldn't have over a long weekend.

**Comment by nantiferov** [comment]
So basically this action is pretty useless if one uses Draft PRs?
This is already quite old GH feature, but official action doesn't support it.
Are there any plans to fix that somehow?

I don't worry much about amount of API calls, we usually have not so much PRs, so why not add this? Or improve GH API to contain this info?

**Comment by C0ZEN** [comment]
@nantiferov one way that already exists is to add a specific label for draft PRs, so you can omit the stale on it.
It's not convenient though because most repositories are not allowing contributors to add a label.

Regarding what the stale action can do, I am in favor of adding a new option which allow people to ignore draft PRs even if we need an extra endpoint call.
Like the https://github.com/actions/stale/issues/359 feature request, we can simply warn and discourage such kind of option for consumers that care about API rate limit, but giving this choice is significant IMO.
I am interested in providing such PR BTW.

**Comment by C0ZEN** [comment]
@luketomlinson can you reopen?
