### ISSUE TITLE
[Feature] Add label when stale issue gets a response

### ISSUE THREAD

**Issue by BenVillalobos** [actions/stale#460]
## The problem
When the issue is marked as stale AND the author responds, the issue will continue to be marked as stale and MSBuild wants to avoid this scenario. See [this example in this repo](https://github.com/actions/stale/issues/288)
## The solution
Add some sort of `add-labels-when-updated-from-stale` and `remove-labels-when-updated-from-stale` to allow this automation:

1. Github action checks only X label for stale-ness
2. After 30 days of inactivity, mark issues with X label as stale
3. Customer responds
4. Action should remove stale label AND remove X label so prevent action from marking as stale again. It could also add some sort of "needs team response" label.

**Comment by C0ZEN** [comment]
@BenVillalobos I agree with this.
The logic of the stale action is mostly to clean up but only when it's logical to do it.
And when the ball is in the maintainers of a given project it's not nice for the author to keep un-stale and un-stale again.

I like the ideas you proposed because it gives a lot of possibility from the consumer side, and it's not altering the main logic of the workflow.
It's just extra optional steps.

Do you wish to provide a PR?

**Comment by BenVillalobos** [comment]
@C0ZEN Sure, could you point me in the right direction of where to add the logic?

**Comment by C0ZEN** [comment]
@BenVillalobos the main logic should be added in https://github.com/actions/stale/blob/main/src/classes/issues-processor.ts.
I think the logic should be after https://github.com/actions/stale/blob/4586dc972d16ceec4afcef82779f2e1cf0293e04/src/classes/issues-processor.ts#L572
As well as
https://github.com/actions/stale/blob/4586dc972d16ceec4afcef82779f2e1cf0293e04/src/classes/issues-processor.ts#L284
Since it's at this moment that the stale label will be removed.

The options should be optionals (if empty string).
Maybe we need to think also about `add-labels-when-updated-from-stale` option which bring new labels and maybe in some cases we should get rid of them. Maybe KISS for now and shall see with time and feature requests.

**Comment by C0ZEN** [comment]
I also think that you need to split the options in half between pr and issue and allow a comma separated list of labels.
