### ISSUE TITLE
Action version vs examples

### ISSUE THREAD

**Issue by jakeatoms** [actions/stale#60]
Hi all! I'm trying to make use of the latest version of the action, which according to the Marketplace, is v2.0.0. However, the docs in this repo show `actions/stale@v1.1.0` or `actions/stale@v1`. Should I be using `actions/stale@v2`? I'd appreciate any clarification on this, thanks!

**Comment by mollyIV** [comment]
Hey @jakeatoms 👋 

In your workflows, you can reference specific versions of actions using tag, branch, or commit SHA. You can find more details about versioning GitHub Actions [here](https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action).

In order to find the newest released version of the action, I'd suggest to have a look at [Releases](https://github.com/actions/stale/releases). 

The docs included in `README.md` file just show an example of how to use the action, so there's no need for pointing to the newest released version there every release 😉 

If you've been using `actions/stale@v1` and want to update to `actions/stale@v2`, please note that according to [Semantic Versioning](https://semver.org/) MAJOR version upgrade brings incompatible API changes.
