### ISSUE TITLE
[Question] operations-per-run parameter?

### ISSUE THREAD

**Issue by doctorperceptron** [actions/stale#79]
What exactly is the `operations-per-run` parameter? I tried running this action in my repo in debug mode and got a warning "Reached max number of operations to process. Exiting." without any other output.

**Comment by aandergr** [comment]
I also wondered about the warning "Reached max number of operations to process. Exiting." after updating from v1 to v3 and doing some other changes in my configuration. 

`operations-per-run` is meant to be "The maximum number of operations per run, used to control rate limiting." During the action's run, the number of operations is counted, where with having a brief look at the code, the following operations seems to count:
- Accessing a page of issues is **one operation** (issues – filtered by state 'open' and onlyLabels – are processed in pages of 100 issues each)
- Closing a stale issue is **one operation**
- Removing a stale label is **one operation**
- Processing an issue that is stale is **one or two operations**, one each for obtaining its date of being marked stale and for checking whether it is still stale 
- Marking an issue stale is **four operations**: Two are counted in https://github.com/actions/stale/blob/96b682d29f2b26168a8b283c62da1ad3f1262120/src/IssueProcessor.ts#L172 plus two in https://github.com/actions/stale/blob/96b682d29f2b26168a8b283c62da1ad3f1262120/src/IssueProcessor.ts#L303 I guess this should be 2 (create comment + add label), rather than 4.

Further, it seems that only after processing a complete page of issues it is checked whether there are still operations left, so the first 100 issues seem to be always processed regardless the `operations-per-run` parameter, making it hard to limit the stale action to only process a few issues at a time.

**Comment by doctorperceptron** [comment]
Thanks @aandergr. What's the purpose of limiting the number of operations? Can we turn this off, to guarantee all the issues are processed?

**Comment by aandergr** [comment]
One of the purposes is to ensure to remain within the [Rate Limiting of GitHub's API](https://developer.github.com/v4/guides/resource-limitations/). As mentioned in the linked article, the API backend computes a score (called *cost* or *point cost*) for each request. Within a 60-minute-window, only a certain number of points can be used up. When that number is reached, requests are blocked until the rate limit window resets. It is wise that actions/stale has some rough awareness of that fact, since hitting the limit in the middle of an operation can produce bad results (e.g. "mark stale" = "create comment"+"add label" is not atomic and must not be interrupted after "create comment"). So better don't turn it entirely off (if that's possible at all; however most probably you can set it to a higher value). However, I didn't estimate how much point cost is actually used in a typical run, also the action's internal operation counter does not resemble the cost computation described in the API documentation – which is okay given that most certainly its main purpose is to have *some* way to ensure that it doesn't come close to using up all the points.

Another purpose may be, when freshly set up in a repository that has many stale issues, to ensure that it closes only a few issues per day rather than very many at once. However, that requires the action to check more often whether the maximum number of operations is already reached, which I try to fix with my abovely-linked PR.

**Comment by hross** [comment]
this. I'll leave this open to potentially do checking before the first run in order to bail out before the limit is hit.

**Comment by hross** [comment]
Fixed here: https://github.com/actions/stale/issues/79
